// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxdxrerolnnzuqexqhly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4ZHhyZXJvbG5uenVxZXhxaGx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzE0NTEsImV4cCI6MjA2NTU0NzQ1MX0.v8gmb5MNjGsZ1tRuOjC4F9xlqFZlm_qrC9MsVFwH584";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);